name: depth
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8 # zoe 3.9.7
  - pytorch::pytorch=2.0.1 # unidepth 2.2.0 (-> )
  - torchvision=0.15.2 # unidepth 0.17.0
  - torchaudio=2.0.2 # unidepth 2.2.0
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch-mutex=1.0
  - nvidia::cuda=11.8
  - cudatoolkit=11.8
  - pip=22.3.1
  - numpy=1.23.1
  - h5py=3.7.0
  - hdf5=1.12.2
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - opencv=4.6.0
  - scipy=1.10.0
  - pip:
    - imutils==0.5.4
    - timm==0.6.12
    - einops==0.6.0 # unidepth 0.7.0
    - huggingface-hub==0.11.1 # unidepth 0.22.0
    - tqdm==4.64.1
    - wandb==0.13.9
    - pillow==10.2.0
    - idna
    - xformers == 0.0.21 # unidepth 0.0.24